package changescope

import (
	"fmt"
	"io"
	"strings"
)

// RenderPRSummaryMarkdown writes a PR-ready markdown summary.
func RenderPRSummaryMarkdown(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	line("## Hamlet — Change Analysis")
	line("")

	// Posture badge.
	badge := postureBadge(pr.PostureBand)
	line("**Posture:** %s %s", badge, strings.ToUpper(pr.PostureBand))
	line("")

	// Summary stats.
	line("| Metric | Count |")
	line("|--------|-------|")
	line("| Changed files | %d |", pr.ChangedFileCount)
	line("| Changed source files | %d |", pr.ChangedSourceCount)
	line("| Changed test files | %d |", pr.ChangedTestCount)
	line("| Impacted code units | %d |", pr.ImpactedUnitCount)
	line("| Protection gaps | %d |", pr.ProtectionGapCount)
	line("")

	// Findings.
	if len(pr.NewFindings) > 0 {
		line("### Findings")
		line("")
		limit := 10
		if len(pr.NewFindings) < limit {
			limit = len(pr.NewFindings)
		}
		for _, f := range pr.NewFindings[:limit] {
			icon := severityIcon(f.Severity)
			line("- %s **%s** `%s`: %s", icon, f.Type, f.Path, f.Explanation)
			if f.SuggestedAction != "" {
				line("  - Action: %s", f.SuggestedAction)
			}
		}
		if len(pr.NewFindings) > limit {
			line("- ... and %d more finding(s)", len(pr.NewFindings)-limit)
		}
		line("")
	}

	// Recommended tests with reasoning.
	if len(pr.TestSelections) > 0 {
		line("### Recommended Tests")
		line("")
		if pr.SelectionExplanation != "" {
			line("*%s*", pr.SelectionExplanation)
			line("")
		}
		limit := 15
		if len(pr.TestSelections) < limit {
			limit = len(pr.TestSelections)
		}
		line("| Test | Confidence | Why |")
		line("|------|------------|-----|")
		for _, t := range pr.TestSelections[:limit] {
			why := t.Relevance
			if len(t.Reasons) > 0 {
				why = deduplicateReasons(t.Reasons)
			}
			if len(t.CoversUnits) > 0 {
				why += fmt.Sprintf(" (covers %d unit(s))", len(t.CoversUnits))
			}
			line("| `%s` | %s | %s |", t.Path, t.Confidence, why)
		}
		if len(pr.TestSelections) > limit {
			line("")
			line("...and %d more test(s).", len(pr.TestSelections)-limit)
		}
		line("")
	} else if len(pr.RecommendedTests) > 0 {
		line("### Recommended Tests")
		line("")
		limit := 15
		if len(pr.RecommendedTests) < limit {
			limit = len(pr.RecommendedTests)
		}
		for _, t := range pr.RecommendedTests[:limit] {
			line("- `%s`", t)
		}
		if len(pr.RecommendedTests) > limit {
			line("- ... and %d more", len(pr.RecommendedTests)-limit)
		}
		line("")
	}

	// Affected owners.
	if len(pr.AffectedOwners) > 0 {
		line("### Affected Owners")
		line("")
		for _, o := range pr.AffectedOwners {
			line("- %s", o)
		}
		line("")
	}

	// Limitations.
	if len(pr.Limitations) > 0 {
		line("<details><summary>Limitations</summary>")
		line("")
		for _, l := range pr.Limitations {
			line("- %s", l)
		}
		line("")
		line("</details>")
		line("")
	}

	line("---")
	line("*Generated by [Hamlet](https://github.com/pmclSF/hamlet) — signal-first test intelligence*")
}

// RenderPRCommentConcise writes a concise PR comment suitable for inline use.
func RenderPRCommentConcise(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	badge := postureBadge(pr.PostureBand)
	line("%s **Hamlet:** %s", badge, pr.Summary)

	if len(pr.NewFindings) > 0 {
		highCount := 0
		for _, f := range pr.NewFindings {
			if f.Severity == "high" {
				highCount++
			}
		}
		if highCount > 0 {
			line("  - %d high-severity finding(s) require attention", highCount)
		}
	}

	if len(pr.TestSelections) > 0 {
		paths := make([]string, 0, len(pr.TestSelections))
		for _, t := range pr.TestSelections {
			paths = append(paths, t.Path)
		}
		line("  - Run %d test(s): %s", len(paths), strings.Join(paths, ", "))
	} else if len(pr.RecommendedTests) > 0 {
		line("  - Run: %s", strings.Join(pr.RecommendedTests, ", "))
	}
}

// RenderCIAnnotation writes CI-annotation-style output.
func RenderCIAnnotation(w io.Writer, pr *PRAnalysis) {
	for _, f := range pr.NewFindings {
		level := "notice"
		switch f.Severity {
		case "high":
			level = "error"
		case "medium":
			level = "warning"
		}
		fmt.Fprintf(w, "::%s file=%s::%s\n", level, f.Path, f.Explanation)
	}
}

// RenderChangeScopedReport writes a human-readable change-scoped report.
func RenderChangeScopedReport(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	blank := func() { fmt.Fprintln(w) }

	line("Hamlet — Change-Scoped Analysis")
	line(strings.Repeat("=", 40))
	blank()

	line("Posture:   %s", strings.ToUpper(pr.PostureBand))
	line("Files:     %d changed (%d source, %d test)", pr.ChangedFileCount, pr.ChangedSourceCount, pr.ChangedTestCount)
	line("Units:     %d impacted", pr.ImpactedUnitCount)
	line("Gaps:      %d", pr.ProtectionGapCount)
	blank()

	if len(pr.NewFindings) > 0 {
		line("Findings")
		line(strings.Repeat("-", 40))
		for _, f := range pr.NewFindings {
			line("  [%s] %s — %s", strings.ToUpper(f.Severity), f.Path, f.Explanation)
		}
		blank()
	}

	if len(pr.TestSelections) > 0 {
		line("Recommended Tests")
		line(strings.Repeat("-", 40))
		if pr.SelectionExplanation != "" {
			line("  Strategy: %s", pr.SelectionExplanation)
			blank()
		}
		for _, t := range pr.TestSelections {
			why := t.Relevance
			if len(t.Reasons) > 0 {
				why = deduplicateReasons(t.Reasons)
			}
			line("  [%s] %s", t.Confidence, t.Path)
			line("         %s", why)
		}
		blank()
	} else if len(pr.RecommendedTests) > 0 {
		line("Recommended Tests")
		line(strings.Repeat("-", 40))
		for _, t := range pr.RecommendedTests {
			line("  %s", t)
		}
		blank()
	}

	if len(pr.AffectedOwners) > 0 {
		line("Affected Owners: %s", strings.Join(pr.AffectedOwners, ", "))
		blank()
	}

	if len(pr.Limitations) > 0 {
		line("Limitations")
		line(strings.Repeat("-", 40))
		for _, l := range pr.Limitations {
			line("  %s", l)
		}
		blank()
	}
}

func postureBadge(band string) string {
	switch band {
	case "well_protected":
		return "[PASS]"
	case "partially_protected":
		return "[WARN]"
	case "weakly_protected":
		return "[RISK]"
	case "high_risk":
		return "[FAIL]"
	default:
		return "[????]"
	}
}

func deduplicateReasons(reasons []string) string {
	seen := map[string]int{}
	var unique []string
	for _, r := range reasons {
		seen[r]++
		if seen[r] == 1 {
			unique = append(unique, r)
		}
	}
	var parts []string
	for _, r := range unique {
		if seen[r] > 1 {
			parts = append(parts, fmt.Sprintf("%s (%dx)", r, seen[r]))
		} else {
			parts = append(parts, r)
		}
	}
	return strings.Join(parts, "; ")
}

func severityIcon(severity string) string {
	switch severity {
	case "high":
		return "[HIGH]"
	case "medium":
		return "[MED]"
	case "low":
		return "[LOW]"
	default:
		return "[---]"
	}
}
